[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
fuzz_runs = 256
verbosity=3
#sender = '0x9d1253e74A084EDC16122E31EEd085855714f513'
#tx_origin = '0x9d1253e74A084EDC16122E31EEd085855714f513'
ffi=true

# See more config options https://github.com/gakonst/foundry/tree/master/config